# PyTorch Lightning trainer configuration

_target_: pytorch_lightning.Trainer

max_epochs: ${max_epochs}
accelerator: auto
devices: auto
precision: 16-mixed
gradient_clip_val: 1.0
accumulate_grad_batches: 1
check_val_every_n_epoch: 1
log_every_n_steps: 50
enable_checkpointing: true
enable_progress_bar: true
enable_model_summary: true
deterministic: ${deterministic}
benchmark: ${benchmark}
