# Hydra Optuna sweep configuration

# @package _global_
defaults:
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
    direction: maximize
    study_name: cifar10_optimization
    storage: null
    n_trials: 20
    n_jobs: 1
    
    # Define search space
    params:
      model.learning_rate: choice(0.0001, 0.001, 0.01)
      model.weight_decay: choice(1e-5, 1e-4, 1e-3)
      model.dropout_rate: choice(0.3, 0.5, 0.7)
      model.hidden_dim: choice(256, 512, 1024)
      data.batch_size: choice(16, 32, 64)
      trainer.max_epochs: 30

# Override some settings for sweep
experiment_name: "cifar10_sweep"
max_epochs: 30
